[package]
name = "auth-service"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = { version = "0.5", features = ["std"] }
diesel = { version = "2.2.0", features = ["postgres","uuid"] }
serde = "1.0.228"
dotenvy = "0.15"
uuid = "1.19.0"
